### ISSUE TITLE
Bug: Enable notifications for all users (Elgg 2.2.2)

### ISSUE THREAD

**Issue by rohit1290** [juho-jaakkola/elgg-notification_tools#2]
- I have a user with following settings:
![1](https://cloud.githubusercontent.com/assets/2772844/20039268/fa253774-a466-11e6-9b35-1fcbfb950420.PNG)

- Now Suppose I want to disable email notification and enable site notification for all user. I selected this:
![2](https://cloud.githubusercontent.com/assets/2772844/20039253/cfda6bb0-a466-11e6-9d9c-578f4d0137ff.PNG)

- After I click on submit. This is what I get:
![3](https://cloud.githubusercontent.com/assets/2772844/20039259/d7a99262-a466-11e6-81f9-6592e9b9590c.PNG)

The email notification that I wanted to disabled remained the same. It didn't change that setting.

**Comment by juho-jaakkola** [comment]
The feature is working as intended, as it is meant only for enabling notification settings, but for disabling them.

I guess I would accept a patch, that would introduce the possibility to also disable notification methods. There is no harm in it, as long as the UI clearly states that all unchecked methods will become disabled.
